version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py36
      - test-py37
      - black-py37
      - interop-chrome
jobs:
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py36
  test-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py37
  black-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e black
  interop-chrome:
    docker:
      - image: public/grpc-web-frontend-tests:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python3 python3-pip
      - run: pip3 install grpcio-tools grpcio requests
      - run: |
          python3 -m grpc.tools.protoc \
            --proto_path=$(pwd) \
            --python_out=. \
            --grpc_python_out=. \
            $(pwd)/echo/echo.proto
      - run:
          background: true
          command: PYTHONPATH=.:$PYTHONPATH python3 echo/server.py
      - run:
          working_directory: /home/node/src
          command: ./node_modules/.bin/grunt karma:improbable --grpc-host=http://localhost:8080
      - run:
          working_directory: /home/node/src
          command: ./node_modules/.bin/grunt karma:grpcWeb --grpc-host=http://localhost:8080
