version: 2
workflows:
  version: 2
  test:
    jobs:
      - build-sonora-images
      - build-grpcweb-images
      - test-py37
      - test-py38
      - lint
      - interop-grpcweb-wsgi:
          requires:
            - build-sonora-images
            # - build-grpcweb-images
      - interop-grpcweb-asgi:
          requires:
            - build-sonora-images
            # - build-grpcweb-images
jobs:
  build-sonora-images:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: |
            docker-compose build
            docker login --username=public --password=$DOCKER_HUB_PAT
            docker tag public/sonora-test-wsgi-server public/sonora-test-wsgi-server:$CIRCLE_SHA1
            docker push public/sonora-test-wsgi-server:$CIRCLE_SHA1
            docker tag public/sonora-test-asgi-server public/sonora-test-asgi-server:$CIRCLE_SHA1
            docker push public/sonora-test-asgi-server:$CIRCLE_SHA1
  build-grpcweb-images:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: Build
          command: |
            git clone https://github.com/grpc/grpc-web.git
            cd grpc-web
            git reset --hard 1.2.1
            docker pull public/sonora-grpcweb-interop
            docker-compose build common prereqs node-interop-server interop-client
            docker login --username=public --password=$DOCKER_HUB_PAT
            docker tag grpcweb/prereqs public/sonora-grpcweb-interop:$CIRCLE_SHA1
            docker push public/sonora-grpcweb-interop:$CIRCLE_SHA1
  test-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: sudo apt-get install python3-dev libev-dev
      - restore_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-master
      - run: tox -e py37 -- --benchmark-save=${CIRCLE_BRANCH} --benchmark-compare
      - save_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
          - .benchmarks
  test-py38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: sudo pip install tox
      - run: sudo apt-get install python3-dev libev-dev
      - restore_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-master
      - run: tox -e py38 -- --benchmark-save=${CIRCLE_BRANCH} --benchmark-compare
      - save_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
          - .benchmarks
  test-py39:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install tox
      - run: sudo apt-get install python3-dev libev-dev
      - restore_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-master
      - run: tox -e py39 -- --benchmark-save=${CIRCLE_BRANCH} --benchmark-compare
      - save_cache:
          key: benchmarks-{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ .Revision }}
          paths:
          - .benchmarks
  interop-grpcweb-wsgi:
    docker:
      - image: public/sonora-grpcweb-interop
      - image: public/sonora-test-wsgi-server:$CIRCLE_SHA1
    steps:
      - run:
          command: /github/grpc-web/scripts/docker-run-interop-tests.sh
  interop-grpcweb-asgi:
    docker:
      - image: public/sonora-grpcweb-interop
      - image: public/sonora-test-asgi-server:$CIRCLE_SHA1
    steps:
      - run:
          command: /github/grpc-web/scripts/docker-run-interop-tests.sh
  lint:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e black