version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-py36
      - test-py37
      - black-py37
      - interop-chrome
jobs:
  test-py36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py36
  test-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e py37
  black-py37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo pip install tox
      - run: tox -e black
  interop-chrome:
    docker:
      - image: public/grpc-web-frontend-tests:latest
        entrypoint: /bin/bash
    steps:
      - checkout
      - run: pip3 install -e .
      - run: |
          python -m grpc.tools.protoc \
            --proto_path=../grpcWSGI \
            --python_out=. \
            --grpc_python_out=. \
            ../grpcWSGI/echo/echo.proto
      - run:
          background: true
          command: python echo/server.py
      - run: ./node_modules/.bin/grunt karma:$1 --grpc-host=http://localhost:8080
